Replaced SERNO_STN with visit_key. Functionality to read also dv template.
nodc-sweden/qc-tool pull request #62
Opened 2024-10-02 17:52 UTC by ylvaeSMHI

pyproject.toml should point to main brain of SHARKadm until next release. Newest version of nodc_codes should also be used.

2024-10-03 08:50 UTC, jonatanmindroad requested changes

2024-10-03 08:50 UTC, jonatanmindroad commented on src/qc_tool/data_transformation.py
> +    # data["SERNO_STN"] = data["SERNO"] + " - " + data["STATN"]
Ta bort raden helt istället, det finns ingen vits att spara den utkommenterad. Vill vi ha tillbaka den så finns den i historiken.

2024-10-03 09:48 UTC, jonatanmindroad commented on src/qc_tool/data_transformation.py
> +    # data["SERNO_STN"] = data["SERNO"] + " - " + data["STATN"]
En till ändring som behöver göras är att byta version på sharkadm i dependencies. Branchen `54-export-till-mappad-dataframe` finns inte längre. Jag borde ha upptäckt det tidigare.

2024-10-03 09:49 UTC, jonatanmindroad commented on src/qc_tool/data_transformation.py
> +    # data["SERNO_STN"] = data["SERNO"] + " - " + data["STATN"]
Eller så gör jag den ändringen nu och så får du göra en rebase mot main.

2024-10-03 15:05 UTC, ylvaeSMHI commented on src/qc_tool/data_transformation.py
> +    # data["SERNO_STN"] = data["SERNO"] + " - " + data["STATN"]
Snyggt, hade jag läst här istället för i mattermost kanske det hade gått bättre, nu har jag inte rätt på rebase ser jag, men lyckade i alla fall pusha de sista ändringarna angående import av pandas och ta bort den utkommenterade raden. är det ok att mergea nu även om pyproject.toml skiljer sig åt? eller måste jag push pyproject.toml så att den matchar med main?

2024-10-04 07:11 UTC, jonatanmindroad approved these changes

2024-10-04 07:11 UTC, merged